services:
  syncthing-client:
    image: syncthing/syncthing:latest
    container_name: syncthing-client
    hostname: syncthing-client
    ports:
      - "${SYNCTHING_GUI_PORT}:8384"
      - "${SYNCTHING_SYNC_TCP_PORT}:22000/tcp"
      - "${SYNCTHING_SYNC_UDP_PORT}:22000/udp"
      - "${SYNCTHING_DISCOVERY_PORT}:21027/udp"
    volumes:
      - ./config:/var/syncthing/config
      - ${SYNCHED_FOLDER_ROOT}:/var/syncthing
      - ${CLIENT_SYNC_ROOT_HOST:-./data}:/sync
    restart: unless-stopped